# ────────────────────────────────────────────────
# Netlify config – no site build, only Edge Fns
# ────────────────────────────────────────────────
[build]
  # No “npm install”, no “npm run build”
  command = "echo 'skip site build'"
  publish = "."                 # nothing to deploy except edge fns

[functions]
  node_bundler = "esbuild"      # default, keeps edge bundle small

[[edge_functions]]
  function = "data"             # handles /data and /data.json
  path     = "/data"
  cache    = "manual"

[[edge_functions]]
  function = "data"
  path     = "/data.json"
  cache    = "manual"

[[edge_functions]]
  function = "data-page"        # pretty HTML view
  path     = "/data.html"
  cache    = "manual"
