[build]
  publish = "public"

[[edge_functions]]
  path     = "/data"
  function = "data"
  cache    = "manual"

[[edge_functions]]
  path     = "/data.json"
  function = "data"
  cache    = "manual"
