[build]
  publish = "public"

# Edge function routes (unchanged, if you still need them)
[[edge_functions]]
  path     = "/data"
  function = "data"
  cache    = "manual"

[[edge_functions]]
  path     = "/data.json"
  function = "data"
  cache    = "manual"

[[edge_functions]]
  path     = "/data.html"
  function = "data-page"
  cache    = "manual"

# Prevent SPA fallback from overriding /data.json
[[redirects]]
  from   = "/data.json"
  to     = "/data.json"
  status = 200
  force  = true

# SPA fallback
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
