[build]
  publish = "public"

[[edge_functions]]
  path     = "/data"
  function = "data"
  cache    = "manual"

[[edge_functions]]
  path     = "/data.json"
  function = "data"
  cache    = "manual"

[[edge_functions]]
  path     = "/data.html"
  function = "data-page"
  cache    = "manual"

[[redirects]]
  from   = "/data.json"
  to     = "/data.json"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
