name: scrape-and-alert

on:
  schedule:
    - cron: '*/15 * * * *'   # every 15 min UTC
  workflow_dispatch:

# Default permissions are read-only; we override for the push step.
permissions:
  contents: write   # grants write access to the repo for all jobs

jobs:
  update-live-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true   # make GITHUB_TOKEN available to git

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build public/live.json
        run: |
          mkdir -p public
          node netlify/edge-functions/data.js > public/live.json

      - name: Commit & push public/live.json
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add public/live.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci: refresh live.json"
            git push
          fi

  alert-telegram:
    needs: update-live-json
    runs-on: ubuntu-latest
    permissions:
      contents: read    # only needs read access here
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run alert script
        run: npm run alert
