# .github/workflows/update-live.yml
name: refresh-live-json

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Generate live.json
        run: npm run generate-live

      - name: Commit & push updated live.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/live.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: refresh live.json"
            git push
          else
            echo "No changes"
          fi
