# .github/workflows/update-live.yml
name: refresh-live-json

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch live.json from Netlify Edge
        run: |
          echo "▶ mkdir -p public"
          mkdir -p public
          echo "▶ curl data.json → public/live.json"
          curl -sSL https://btcsignal.netlify.app/data.json -o public/live.json

      - name: Debug generated JSON
        run: |
          echo "🔍 public folder contents:"
          ls -al public
          echo "⏱ public/live.json head:"
          head -n20 public/live.json
          echo "…"
          echo "⏱ public/live.json tail:"
          tail -n20 public/live.json

      - name: Commit & push updated live.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email  "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/live.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: refresh live.json"
            git push
          else
            echo "No changes"
          fi
