name: refresh-live-json

permissions:
  contents: write

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install & generate live.json
        env:
          EDGE_URL: "https://btcsignal.netlify.app/data.json"
        run: |
          echo "▶ npm install"
          npm install
          echo "▶ npm run generate-live"
          npm run generate-live

      - name: Debug live.json
        run: |
          echo "🔍 public folder:"
          ls -al public
          echo "⏱ live.json preview:"
          head -n10 public/live.json
          echo "…"
          tail -n10 public/live.json

      - name: Commit & push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/live.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: refresh live.json"
            git push
          else
            echo "No changes"
          fi
