# .github/workflows/update-live.yml
name: refresh-live-json

# allow commits
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install deps & generate live.json
        env:
          NPM_CONFIG_LOGLEVEL: verbose
        run: |
          echo "▶ npm install"
          npm install
          echo "▶ npm run generate-live"
          npm run generate-live

      - name: Debug generated JSON
        run: |
          echo "::group::public folder contents"
          ls -al public
          echo "::endgroup::"
          echo "::group::live.json head"
          head -n20 public/live.json
          echo "::endgroup::"
          echo "::group::live.json tail"
          tail -n20 public/live.json
          echo "::endgroup::"

      - name: Commit & push updated live.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/live.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: refresh live.json"
            git push
          else
            echo "No changes"
          fi
