# .github/workflows/update-live.yml
name: refresh-live-json

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show generate-live.js (for verification)
        run: |
          echo '--- scripts/generate-live.js head ---'
          head -n50 scripts/generate-live.js
          echo '--- end ---'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          echo "▶ npm install"
          npm install

      - name: Generate live.json from Edge
        env:
          EDGE_URL: "https://btcsignal.netlify.app/data.json"
        run: |
          echo "▶ npm run generate-live"
          npm run generate-live

      - name: Debug generated JSON
        run: |
          echo "🔍 public folder contents:"
          ls -al public
          echo "⏱ public/live.json head:"
          head -n20 public/live.json
          echo "…"
          echo "⏱ public/live.json tail:"
          tail -n20 public/live.json

      - name: Commit & push updated live.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/live.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: refresh live.json"
            git push
          else
            echo "No changes"
          fi
