name: refresh-live-json

permissions:
  contents: write   # ← gives the default token push rights

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with: { node-version: "18" }

      - name: Install (creates lockfile if missing)
        run: npm install

      - name: Build live.json
        run: npm run generate-live

      - name: Commit & push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/live.json package-lock.json || true
          if git diff --cached --quiet; then
            echo "ℹ️  nothing to commit"
            exit 0
          fi
          git commit -m "chore: refresh live.json"
          git push origin HEAD:main
