name: refresh-live-json
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: { node-version: "18" }

      - run: npm run generate-live

      - name: Commit & push
        env: { GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/live.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: refresh live.json"
            git push
          else
            echo "No changes"
          fi
